name: Django CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

#NOTES: 
# - For consistency, using PIP in virtual unbuntu environment instead of anaconda
# - 
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
      
        # Variables Used
        variables:
        - name: programEntry
          value: ap_src/manage.py
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install Application Dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
        
        python -m pip install seleniumbase
        sbase get chromedriver latest
    - name: Set up Django Environment
      run: |
        echo "Making Migrations"
        python3 ap_src/manage.py makemigrations
        echo "Running Migrations"
        python3 ap_src/manage.py migrate ap_app
        python3 ap_src/manage.py migrate

        echo "Loading Fixtures"
        for FILE in ap_src/ap_app/fixtures/*; 
        do python3 ap_src/manage.py loaddata $FILE; done
        
        echo "Collecting Static Files"
        python3 ap_src/manage.py collectstatic --noinput

    - name: Install Testing Dependencies
      run: |
        pip3 install pytest
        pip3 install pytest-django
        pip3 install coverage
        pip3 install pytest-cov

    - name: Run Tests
      run: |
        pwd
        echo "Going into 'ap_src' Directory to execute pytests"
        cd ap_src
        echo Running Application Tests With SeleniumBase
        pytest --cov=ap_app ap_src/ap_app
        
        

        