name: Django CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

    
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
      
        # Variables Used
        variables:
        - name: programEntry
          value: ap_src/manage.py
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Set up Django Environment
      run: |
        echo "Making Migrations"
        python3 ap_src/manage.py makemigrations
        echo "Running Migrations"
        python3 ap_src/manage.py migrate ap_app
        
        for F in ap_src/ap_app/fixtures/*; 
        do python3 ap_src/manage.py loaddata $F; done
        

    - name: Run Tests
      run: |
        pytest ap_src/ap_app/tests.py
